import { createSlice } from "@reduxjs/toolkit";

const initialState = {
  file: "data:application/octet-stream;base64,RXhwb3J0ZWQgZnJvbSBCbGVuZGVyLTIuOTAuMQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMAAAAAACAvwAAAAAAAAAA0MzMvdDMzL3QzMy90MzMvdDMzL3QzMw90MzMvdDMzD3QzMw9AAAAAIC/AAAAAAAAAADQzMy90MzMvdDMzL3QzMy90MzMPdDMzD3QzMy90MzMPdDMzL0AAAAAAAAAAIA/AAAAANDMzL3QzMw90MzMvdDMzL3QzMw90MzMPdDMzD3QzMw90MzMPQAAAAAAAAAAgD8AAAAA0MzMvdDMzD3QzMy90MzMPdDMzD3QzMw90MzMPdDMzD3QzMy9AAAAAIA/AAAAAAAAAADQzMw90MzMPdDMzL3QzMw90MzMPdDMzD3QzMw90MzMvdDMzD0AAAAAgD8AAAAAAAAAANDMzD3QzMw90MzMvdDMzD3QzMy90MzMPdDMzD3QzMy90MzMvQAAAAAAAAAAgL8AAAAA0MzMPdDMzL3QzMy90MzMPdDMzL3QzMw90MzMvdDMzL3QzMw9AAAAAAAAAACAvwAAAADQzMw90MzMvdDMzL3QzMy90MzMvdDMzD3QzMy90MzMvdDMzL0AAAAAAAAAAAAAAACAv9DMzL3QzMw90MzMvdDMzD3QzMw90MzMvdDMzD3QzMy90MzMvQAAAAAAAAAAAAAAAIC/0MzMvdDMzD3QzMy90MzMPdDMzL3QzMy90MzMvdDMzL3QzMy9AAAAAAAAAAAAAAAAgD/QzMw90MzMPdDMzD3QzMy90MzMPdDMzD3QzMy90MzMvdDMzD0AAAAAAAAAAAAAAACAP9DMzD3QzMw90MzMPdDMzL3QzMy90MzMPdDMzD3QzMy90MzMPQAA",
};

const stlSlice = createSlice({
  name: "stl",
  initialState,
  reducers: {
    uploadFile: (state, action) => {
        state.file = action.payload;

    },
  },
});


export default stlSlice.reducer;
export const stlActions = stlSlice.actions;
