/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 link.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/link.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.text.geometry} material={materials.text} />
      <mesh geometry={nodes.text_1.geometry} material={materials.box} />
    </group>
  )
}

useGLTF.preload('/link.glb')
